apiVersion: batch/v1
kind: Job
metadata:
  generateName: olmo3-icd-pred-
  labels:
    kueue.x-k8s.io/queue-name: eidf186ns-user-queue
spec:
  completions: 1
  template:
    metadata:
      name: olmo3-icd-pred
    spec:
      restartPolicy: Never

      containers:
        - name: olmo3-pred
          image: vllm/vllm-openai:v0.21.0

          env:
            - name: HUGGINGFACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: HUGGINGFACE_HUB_TOKEN
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: HUGGINGFACE_HUB_TOKEN

            - name: TOKENIZERS_PARALLELISM
              value: "false"

            - name: HF_HOME
              value: /mnt/app/.cache/huggingface
            - name: TRANSFORMERS_CACHE
              value: /mnt/app/.cache/huggingface/transformers
            - name: HF_DATASETS_CACHE
              value: /mnt/app/.cache/huggingface/datasets

            - name: PYTHONUNBUFFERED
              value: "1"

          command: ["/bin/bash", "-lc"]
          args:
            - |
              set -euo pipefail
              cd /mnt/app

              echo "Installing small Python requirements..."
              python -m pip install --upgrade pip
              python -m pip install pandas pyarrow tqdm transformers safetensors

              echo "Checking runtime versions..."
              python -c 'import torch, vllm; print("torch:", torch.__version__); print("torch cuda:", torch.version.cuda); print("cuda available:", torch.cuda.is_available()); print("vllm:", vllm.__version__)'              

              # echo "Starting vLLM ICD prediction..."

              # python -u predict_vllm_olmo3_icd.py \
              #   --test_file ./icd_data/mimiciv_icd10/val.parquet \
              #   --adapter_dir ./icd_models/olmo3-7b-instruct-mimiciv-icd10-lora-r16-bf16-1 \
              #   --output_file ./outputs/val_predictions_vllm_r16.jsonl \
              #   --metrics_file ./outputs/val_metrics_vllm_r16.json \
              #   --text_col text \
              #   --label_col diagnosis_codes \
              #   --max_model_len 8192 \
              #   --max_tokens 256 \
              #   --batch_size 32

              # echo "Prediction finished."

          volumeMounts:
            - mountPath: /mnt/app
              name: volume
            - mountPath: /dev/shm
              name: dshm

          resources:
            requests:
              cpu: 8
              memory: 64Gi
            limits:
              cpu: 16
              memory: 128Gi
              nvidia.com/gpu: 1

      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-80GB

      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pytorch-pvc

        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi